/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: teryrocks32 (https://sketchfab.com/mohammed_el-tairy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ui-ux-typing-machine-5d717a7a9f0f48e3bfbfcfb465427b55
Title: UI UX typing machine
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/machine.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.White}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/machine.gltf");
