import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/tablet.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 135.939, -12.143]}
        rotation={[2.694, 0, Math.PI]}
        scale={[-117.412, 69.209, 1.648]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Metallic_0.geometry}
          material={materials.Metallic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Metallic_0_1.geometry}
          material={materials.Metallic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Metallic_0_2.geometry}
          material={materials.Metallic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Metallic_0_3.geometry}
          material={materials.Metallic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Metallic_0_4.geometry}
          material={materials.Metallic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Plastic_0.geometry}
          material={materials.Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Plastic_0_1.geometry}
          material={materials.Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Plastic_0_2.geometry}
          material={materials.Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Plastic_0_3.geometry}
          material={materials.Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Plastic_0_4.geometry}
          material={materials.Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Plastic_0_5.geometry}
          material={materials.Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Plastic_0_6.geometry}
          material={materials.Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Plastic_0_7.geometry}
          material={materials.Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Screen_0.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Screen_0_1.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Kevlar_001_0.geometry}
          material={materials.Kevlar_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Glass_0.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_1.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_2.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_3.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_4.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_5.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_6.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_7.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_8.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_9.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_10.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_11.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_12.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_13.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_14.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_15.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_16.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_MetallicWhite_0_17.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_PlasticS_0.geometry}
          material={materials.PlasticS}
        />
      </group>
      <group
        position={[158.423, 120.43, 47.538]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Holder2_Kevlar_001_0.geometry}
          material={materials.Kevlar_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Holder2_PlasticS_0.geometry}
          material={materials.PlasticS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Holder2_Metallic_0.geometry}
          material={materials.Metallic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Holder2_SoftBlack_0.geometry}
          material={materials.SoftBlack}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Holder_PlasticS_0.geometry}
        material={materials.PlasticS}
        position={[0, 170.674, -36.785]}
        rotation={[-0.409, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/tablet.gltf");